apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  - cmp-secrets.yaml
  - oidc-secret.yaml
  - vmservicemonitors.yaml

patches:
  - path: cmp-patch.yaml
  - path: argocd-cm-patch.yaml
  - path: argocd-rbac-cm-patch.yaml
  - path: argocd-cmd-params-cm-patch.yaml
