apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

resources:
  - grafana-secret.yaml
  - tibber-secret.yaml
  - tibber-datasource.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"

configMapGenerator:
  - name: heatpump-dashboard
    files:
      - dashboards/heatpump.json

helmCharts:
  - namespace: grafana
    name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yaml
