apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: renovate
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate
                      key: GITHUB_TOKEN
                - name: RENOVATE_CONFIG_FILE
                  value: "/usr/src/app/config/renovate.json"
              volumeMounts:
                - name: config-volume
                  mountPath: /usr/src/app/config
          restartPolicy: OnFailure
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
