apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate

resources:
  - cronjob.yaml
  - secret.yaml

images:
  - name: renovate/renovate
    newTag: 37.414.1

configMapGenerator:
  - name: renovate-config
    files:
      - renovate.json
