apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: homeassistant
spec:
  jobName: home-assistant
  targetEndpoints:
    - targets:
        - homeassistant.{ MY_DOMAIN }:8123
      scheme: https
      bearerTokenSecret:
        name: homeassistant-token
        key: token
      path: /api/prometheus
      tlsConfig:
        insecureSkipVerify: true
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: husdata
spec:
  jobName: husdata-exporter
  targetEndpoints:
    - targets:
        - homeassistant.{ MY_DOMAIN }:9101
      scheme: http

