apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: k10-httpservicediscovery
spec:
  httpSDConfigs:
    - url: http://metering-svc.k10.svc.cluster.local:8000/v0/listScrapeTargets
  relabelConfigs:
    - targetLabel: job
      replacement: httpServiceDiscovery
