apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kromgo

images:
  - name: ghcr.io/kashalls/kromgo
    newTag: 0.3.1

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: kromgo-config
    files:
      - config.yaml
